# -*- coding: utf-8 -*-
"""trans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Plp_o9EcGTtfnjjACjFAWF-MxU7i_pIE
"""

!pip install transformers

from transformers import pipeline

analyzer = pipeline("sentiment-analysis")

text_input=input('enter some text:')

result=analyzer(text_input)

result

generate = pipeline("text-generation")

statement=input("give any short statement:")

result=generate(statement,max_length=150)

result

entity_rec=pipeline('ner')

text=input('enter some text:')

result=entity_rec(text)

result

q_a=pipeline('question-answering')

result=q_a({
    'question':'what is the moral of this story?',
    'context':"""
    Once upon a time in ancient China, there lived a kind and honest boy named Ping. He loved gardening and was known throughout the village for growing the most beautiful flowers.

One day, the emperor, who had no children, announced a unique way to choose his successor. He called all the children in the kingdom and gave each one a seed.

“These are special seeds,” the emperor said. “Whoever grows the best plant in six months will be the next emperor!”

Ping took his seed home and planted it in a pot with great care. He watered it daily and made sure it got sunlight. But weeks passed, and nothing grew. He changed the soil, tried a new pot, and prayed—but still, the seed didn’t sprout.

Six months later, all the children returned to the palace with beautiful flowers, trees, and vines. Ping came with his empty pot. He felt embarrassed but knew he had done his best.

The emperor looked at all the pots, but when he saw Ping’s empty one, he smiled.

Then he said, “The seeds I gave you were boiled—they could not grow. I wanted to see who would be honest and come with an empty pot. Only Ping has been truthful. He will be the next emperor.”

"""
})

result

summarize = pipeline('summarization')

context = """
      I’ve been using the Noise ColorFit Pulse Smartwatch for the past month, and it has exceeded my expectations for a budget-friendly wearable. The display is bright and clear, even in sunlight, and the touch response is smooth. It tracks steps, heart rate, sleep, and SpO2 quite accurately. The battery lasts about 7-8 days on a single charge, which is impressive.

The companion app is easy to use and syncs data quickly. It also offers customizable watch faces and call/message notifications, which are very convenient. The watch is lightweight and comfortable to wear all day.
"""
"""
"""
"""
"""

while True:
  q=input('enter the question: ')
  if q.lower()=='quit':
    break
  result = qa({
      'question':q,
      'context':context
  })
  print (result['answer'])

import builtins
txt = builtins.input("enter the text: ")

result = summarize(txt)

result

from transformers import pipeline

translator=pipeline('translation_en_to_fr')

text=input('enter some text:')

res=translator(text)

res

f_n = pipeline('fill-mask')

text=input('enter a statement with a black having <mask>:')

res = f_n(text)

res

feature_extraction = pipeline('feature-extraction')

text = 'programming is easy'

res=feature_extraction(text)

res

